# .github/dependabot.yml - Versão Corrigida e Otimizada
version: 2
updates:
  - name: "Atualizações de Pacotes NPM"
    package-manager: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "LipeLacross"
    assignees:
      - "LipeLacross"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "npm"
    automerge: false
    ignore:
      - dependency-name: "typescript@^5.8.3"
      - dependency-name: "nuxt@^3.17.5"

  - name: "Atualizações de GitHub Actions"
    package-manager: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "ci"
    labels:
      - "github-actions"
      - "ci"
    automerge: false
